### ISSUE TITLE
Independent ADC channels?

### ISSUE THREAD

**Issue by deviashin** [sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library#1]
How can you use these examples so that you can use each ADC channel separately?
For example, to measure 4 different external voltages connected to 4 different ADC inputs?

**Comment by PaulZC** [comment]
Hi @deviashin,
Good question!
Please take a look at the [Manual Config example](https://github.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/blob/master/examples/Qwiic_PT100_ADS122C04/Example9_ManualConfig/Example9_ManualConfig.ino). You need to use ```setInputMultiplexer``` to select which input(s) are used for the conversion. The different options are [here](https://github.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/blob/master/src/SparkFun_ADS122C04_ADC_Arduino_Library.h#L105-L119).
Please see section **8.3.1** in the [datasheet](https://github.com/sparkfunX/Qwiic_PT100_ADS122C04/blob/master/Documents/ads122c04.pdf) for more details.
I am going to close this issue as I believe this fully answers your question. But please reopen if required.
Very best wishes,
Paul
