### ISSUE TITLE
Measurement deviations

### ISSUE THREAD

**Issue by deviashin** [sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library#2]
Hello!

Please tell me why your formulas use the ADC value as 2 ^ 23 and not 2 ^ 24? We have a 24-bit ADC, right?

Using the readRawVoltage() function;
This way I get the original value from the ADC.
Next, I need to rebuild it from conventional units into real voltage. Your example indicates that you need to divide the reference voltage by the ADC bit width. Why is there 2 ^ 23?

My problem is that when I get the initial voltage through the example function, I pass this value through a 3.3Ω shunt to measure the current consumption of some device.

By applying current from a lithium battery (3.68V) through a 3.3kΩ resistor, I should get about 1.1mA, but in fact I get 860μA.

Thus, I would like to get an answer to two questions, why is the degree 23 and not 24?
And why am I getting values ​​that are not very close to the calculated ones?

All measurements take place on the lower shoulder relative to the common ground according to the differential scheme.

**Comment by deviashin** [comment]
Using ADS122C04_MUX_AIN1_AIN0 = 0.860mA
Using ADS122C04_MUX_AIN0_AVSS = 1.050mA
Using ADS122C04_MUX_AIN1_AVSS = 0.182mA

Regardless of the accuracy of the values, it is clear that in different modes, the losses are the same, what am I doing wrong?

The shunt is located as close to the pins of the microcircuit as physically possible (almost to the output of the IC)

**Comment by PaulZC** [comment]
Hi @deviashin ,
The ADC output is 24-bit two’s complement. Thus the full scale value (+ve or -ve) is 2^23 not 2^24.
I will think more about your current measurement.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Can you send me a diagram of your circuit?
It is not clear to me if you have only the 3.3Ohm resistor in the circuit.
Are you using the Qwiic PT100? Have you removed all the other filter components?

**Comment by PaulZC** [comment]
Ah! Are you powering the board from 3.3V?
If so, there is your answer. You are trying to measure slightly more than 3.3V. The ADC is almost rail-to-rail but you do need some headroom.
Please close this issue if this answers your questions.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @deviashin ,
Thinking more about this - I really do need to see your circuit diagram.
If I understand you correctly, you are measuring the voltage across a 3.3Ohm resistor and are using a 3.3kOhm resistor to limit the current from the battery? With  approximately 1mA flowing through 3.3Ohms, you expect to see approximately 3.3mV.
```readRawVoltage``` uses the ADS122C04's internal 2.048V reference and a gain of 1, so you should should see values of approximately:
2^23 * 3.3mV / 2.048V = 13517 = 0x34CD
The question - and why I need to see your circuit diagram - is how is your 3.3Ohm resistor connected into the circuit? Is one end connected to ground? Or maybe 3.3V? Or something in between? You need to make sure that the **common mode voltage** stays within the ADC voltage rails. It must not be higher than 3.3V or lower than 0V.
Best wishes,
Paul

**Comment by deviashin** [comment]
It seems the measurement accuracy problem was with the PGA turned on.
In your library, there seems to be an error in declaring defines in the SparkFun_ADS122C04_ADC_Arduino_Library.h file. The PGA is turned off by the active 1, unlike the rest of the registers. Check, please.
I also increased the gain to 4 (in the code itself, I did not forget to divide the resulting value back) and set the lowest speed to 20SPS
The problem seems to have been solved, I don't see much sense in giving the diagram.
Anyway, my problem, albeit indirectly, helped to find an error in the library.
Thank you very much for your help!

**Comment by PaulZC** [comment]
Hi @deviashin ,
I agree - thank you. I have got the PGA enable/disable the wrong way round. Great detective work!
![image](https://user-images.githubusercontent.com/5690545/95098818-0e4d5480-0727-11eb-91c0-a792c6a29576.png)
Many thanks,
Paul
