### ISSUE TITLE
ADS112c04 arduino library

### ISSUE THREAD

**Issue by rabinhod** [sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library#4]
is it possible to use this library for ads112c04 ? if no, then how can convert it for ads112c04 ?

**Comment by PaulZC** [comment]
Hi @rabinhod ,
I’m not familiar with the ADS112. You will need to compare the datasheets and look at the registers in particular. If the registers are similar - and I suspect they will be - then converting the library to the ADS112 should be straightforward.
Best wishes,
Paul

**Comment by rabinhod** [comment]
@PaulZC 
Thank you for reply
I checked it and the main different is ADS112 is 16-Bit and ADS122 is 24-Bit

i'm software development and i'm new in hardware development
can you tell me which  part of library must be change ?
