### ISSUE TITLE
missing getters

### ISSUE THREAD

**Issue by karelv** [sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library#5]
Hello,

May I kindly ask you to add getter functions?

- getSlaveAddress ==> return the private variable _deviceAddress
- getADCMode ==> return the private variable _wireMode

Thanks.

**Comment by PaulZC** [comment]
Hi @karelv ,
Good suggestion. I will add these in v1.0.2.
Best wishes,
Paul
