### ISSUE TITLE
Compatible with  ADS112C04?

### ISSUE THREAD

**Issue by Ben-Anton-Utzer** [sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library#9]
Hi,

guess the library would be also compatible with the ADS112C04 right? As far as I can see only the resolution of the AD-converter is the difference.

BR
Markus

**Comment by PaulZC** [comment]
Hi Markus (@Ben-Anton-Utzer ),

Sadly, it won't work correctly. You will need to modify the library code so it handles the 16-bit data vs. 24-bit data correctly:

![image](https://github.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/assets/5690545/21474bfe-ad41-4cdc-adfb-5f7939e31875)

![image](https://github.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/assets/5690545/920cfe86-9bba-4b63-a526-6d3740ae7612)

You will - as a minimum - need to: change the number of bytes requested from three to two; correctly 'pack' the returned two's-complement data into int32_t. Or change to int16_t everywhere...

Best wishes,
Paul
